### ISSUE TITLE
Notification service keeps running in background

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#456] opened 2020-11-27 02:37 UTC
I saw #323 but I guess that it's better to open a new ticket.

I was taking a look at my running processes when I saw that I have a `AlarmNotifications$Notifica..` running here:

![](https://user-images.githubusercontent.com/982338/100404369-f9fb4900-303f-11eb-8706-094180e9db52.png)

It's in Portuguese, but it's saying that it's running :-)

Since I haven't any kind of alarms in Suntimes, I guess that I shouldn't have anything running in background too, right?

The app version is `0.13.4`

Thanks!

**Comment by forrestguice** [comment] 2020-11-27 03:26
Thanks for the heads up. I'll take another look at this. The service should stop itself when finished, and should only run while scheduling or sounding an alarm.

In the past there have been instances where it was started when it shouldn't have been (like the linked issue), or continued running after it finished. I suspect its the second one - the service was started for some reason 10:56:48 ago (screenshot) and failed to stop itself afterward.

The good news is its just idling and not actually doing anything. It shouldn't cause the app to show up in the battery list, and if pressed for resources Android should kill the process.

**Comment by forrestguice** [comment] 2020-11-27 04:07
Well **** I thought this was fixed but obviously not. 

10:56:48 was probably just a reboot, where its started to reschedule alarms (happens even if there are none). I see it running immediately after device boot :\

**Comment by forrestguice** [comment] 2020-11-27 05:15
It turns out to be the same as #323.  There must have been a regression at some point.. 

We should be ignoring TIME_SET broadcasts but instead they are received. That triggers this thing on a regular basis. I'm guessing that line was accidentally merged back into the manifest at some point. The block of code that responds to the broadcast is completely empty, which is a problem in itself - even if it does nothing it needs to finish by calling `stopService`.

**Closed** 2020-12-05 05:30 UTC
Labels: bug
