### ISSUE TITLE
Sunset/Sunrise widget does not updates automatically

### ISSUE THREAD

**Issue by DarthMazut** [forrestguice/SuntimesWidget#806] opened 2024-06-15 08:52 UTC
**Describe the bug**
Sunset/Sunrise widget does not update automatically. I need to click it in order to display up-to-date values (I've set to update widget on click). 

**To Reproduce**
1. Create widget with Sunset/Sunrise
2. Go to sleep...
3. Look at the widget in the morning: it displays yesterday's values

**Expected behavior**
The widget should display proper values at real time. Like no one expects that a clock requires click on its widget to display correct time...

**Screenshots**
- No provided -

**Version Info:**
 - App Version: 0.15.15 (dea8fef1b)
 - Android Version: 12 SKQ1.211006.001
 - Device Model: Xiaomi 12T Pro, MIUI 13.0.24 (Stable)

My question regarding this is whether this affects sunset/sunrise notifications time?

**Comment by forrestguice** [comment] 2024-06-15 18:33
Thanks for the report.

I'm think this is caused by aggressive battery optimization by your specific device. Unfortunately Xiaomi devices have a reputation for this. It might be possible to fix it by following these [recommendations](https://forrestguice.github.io/Suntimes/help/alarms/recommendations/index.html), or one of the solutions at https://dontkillmyapp.com/.

> My question regarding this is whether this affects sunset/sunrise notifications time?

Very likely. If widgets fail to update, I'm also betting that alarms/notifications fail too (since both rely on the same underlying [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager)).

**Comment by HolyNameSoftware** [comment] 2024-08-07 07:47
Maybe it is a combination of things but mostly having to do with Android OS after android 4 or 5 widgets quit being "live". Was probably also a semi security conscern. BTW why isn't Suntimes on Google play store?

**Comment by philibeur** [comment] 2024-08-11 15:28
Hello, I have the same issue on the Samsung Galaxy a34 5g and not in my old a7(2018), probably the economy battery mode.

**Comment by ericjs** [comment] 2024-08-13 16:38
I have the same problem with the clock widget, on a Pixel 7 Pro, using GrapheneOS. It was updating fine until just recently. Allow background battery usage is enabled.

**Comment by forrestguice** [comment] 2024-08-13 20:11
@ericjs When you say recent, is this something you would attribute to the `v0.16.0` update?

The targetSdk was bumped from 25 to 28 recently, while api26 introduces additional [background restrictions](https://developer.android.com/about/versions/oreo/background#broadcasts). I am thinking that the update broadcast itself might actually be blocked (in which case I'm very sorry, I should have caught it sooner).

**Comment by ericjs** [comment] 2024-08-13 20:48
@forrestguice I wish I could tell you, but I haven't paid close enough attention to updates and don't know if I realized it wasn't updating right away. I can't rule out it having been a GrapheneOS update. Would anything in the logs suggest whether it was or wasn't the update broadcast being blocked?

**Comment by ericjs** [comment] 2024-08-13 20:56
(When I said the logs, I was thinking there were some logs I'd seen in Suntimes, but I think I the logs I was remembering were in a different app. I spent some time thinking my clock widget was from another Clock app before I figured out it was from Suntimes. So my question about logs probably wasn't very helpful, sorry.)

**Comment by ericjs** [comment] 2024-08-13 20:59
I suppose I  should at least clarify that I am running 0.16.0.

**Comment by forrestguice** [comment] 2024-08-14 02:24
@ericjs Thanks for the reply. 
I think I've found the problem, so I'm optimistic this will be fixed in `v0.16.1`.

**Comment by HolyNameSoftware** [comment] 2024-08-14 04:21
Forrest did you delete our discussion about your milestone of trying I use some of your suggestions as a reference no need to delete it.

**Closed** 2024-08-20 16:38 UTC
Labels: bug

**Comment by ericjs** [comment] 2024-08-20 21:34
@forrestguice Thank you!

**Comment by philibeur** [comment] 2024-08-27 19:29
Thank you for the job!
