### ISSUE TITLE
crash when time zone does not exist

### ISSUE THREAD

**Issue by anlalalu** [forrestguice/SuntimesWidget#376] opened 2019-12-12 11:16 UTC
###### Reproduction Steps

1. tap 'Location' and set a wrong name in setting location dialog
2. tap 'Update'
3. tap 'set timezone' where the default time zone will be none
4. tap 'set'

###### Expected Result
A dialog with some information that the location is wrong

###### Actual Result
crash, the stack trace is:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.forrestguice.suntimeswidget, PID: 8615
                                                 java.lang.NullPointerException
                                                     at com.forrestguice.suntimeswidget.TimeZoneDialog.saveSettings(TimeZoneDialog.java:580)
                                                     at com.forrestguice.suntimeswidget.TimeZoneDialog$2.onClick(TimeZoneDialog.java:151)
                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
Android Version = 4.4.4

**Comment by forrestguice** [comment] 2019-12-12 17:38
> where the default time zone will be none

Hrm. What does this look like? The mode is "System Time Zone" and the time zone field is empty? Also, is it possible to switch to "User Defined" and select a time zone from the list?

I think you may be running an older version - I'd be curious to see a stack trace from the latest (v0.12.3).

**Comment by anlalalu** [comment] 2019-12-13 10:46
this is the stack trace in v0.12.3:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.forrestguice.suntimeswidget, PID: 9879
                                                 java.lang.NullPointerException
                                                     at com.forrestguice.suntimeswidget.TimeZoneDialog.saveSettings(TimeZoneDialog.java:547)
                                                     at com.forrestguice.suntimeswidget.TimeZoneDialog$13.onClick(TimeZoneDialog.java:665)
                                                     at android.view.View.performClick(View.java:4438)
                                                     at android.view.View$PerformClick.run(View.java:18422)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

and this is the screen shot before the crash arises:
![image](https://user-images.githubusercontent.com/46981872/70794375-7b7aac80-1dd8-11ea-9e68-e6af11c2efac.png)

**Comment by forrestguice** [comment] 2019-12-13 19:12
Thanks, this is very helpful. I'm also able to reproduce it on my own device (also 4.4.4).

There appears to be a couple things going on here. The crash basically occurs when "set" is pressed while the time zone list is still loading. It takes a moment to load the list (uses AsyncTask) but normally its pretty quick. However setting location to "current (last known)" triggers the bug consistently. In this case the time zone list doesn't finish loading until the location update is completed. I suspect the reason for the delay is probably explained in https://stackoverflow.com/questions/9654148/android-asynctask-threads-limits

Anyhow, the dialog should really validate the input (and disable the button while loading). It'll be fixed in v0.12.4

**Closed** 2020-01-07 19:00 UTC
Labels: bug
