### ISSUE TITLE
Problem with comma as decimal separator

### ISSUE THREAD

**Issue by verdulo** [forrestguice/SuntimesWidget#29] opened 2016-08-07 14:53 UTC
"Get location" feature is not working if the system decimal separator is "," - the program fetches location but cannot interpret it correctly.

**Comment by forrestguice** [comment] 2016-08-07 18:33
confirmed. I will fix this. 
At the moment the input values are being fed straight into the constructor for `BigDecimal` which expects things to be just so. I think doing `NumberFormat.getNumberInstance` w/ the locale as an intermediate step should resolve it. 

In retrospect I am thinking I should have written WidgetSettings.Location to convert and store values as doubles to make things less ambiguous, but its a little late now - messing w/ the storage format creates a mess in other places. :\

**Comment by forrestguice** [comment] 2016-08-08 02:47
@verdulo In countries that use "," as the decimal separator, should the latitude/longitude still display with a "." period? In other words is it always ISO 6709, or should I be formatting to the locale?

**Comment by forrestguice** [comment] 2016-08-08 03:03
If its always "." then I think my initial assumption on this one was wrong. ...nothing to do w/ BigDecimal.

Its not that "," as a separator isn't working right, its that "," shouldn't be allowed as a separator at all in lon/lat, regardless of the locale, but its showing up that way (and then the app fails to interpret it).

If thats the convention, then I think I found the problem. Its this call to `String.format` in WidgetSettings.Location, which I'm (carelessly) using to round the values (and inadvertently localizing the values reported by the gps). :\

**Comment by verdulo** [comment] 2016-08-08 09:58
https://fr.wikipedia.org/wiki/ISO_6709 - examples on this page shows "," as decimal separator, all countries excepting former British Empire and China use "," as decimal separator...

Another thing: on release page you said: 
> lat/lon precision; was unlimited but now rounded to 5 places (meter precision)
maybe it should be even rounded to 4 decimal places, because GPS precision is around 5m (round it to 10m).

**Comment by forrestguice** [comment] 2016-08-08 17:01
hrm, now I'm more confused than ever. I'm aware that "," is the prevalent decimal separator worldwide, but I'm having trouble determining if thats the convention in use with lat/lon in the majority of localized software. It really doesn't seem to be.

http://ux.stackexchange.com/questions/85702/localizing-coordinates suggests that I shouldn't localize these values ever (but seems searchengine specific). Also, the the german and italian versions of google maps (https://www.google.it/maps/) appear to use a "." with lat/lon while the rest of the display values (distance, area, etc) use a "," as expected.

..but I do run into localized examples occasionally, and the spec itself says the separator is left to the operating system, so I'm not sure what the "right thing" is. The "easy thing" is to force the use "." regardless of locale - I am of course biased - I like the easy solution because its a one line fix ;) vs refactoring the entire LocationConfigView. I will do it though if there is a real expectation among international users to see lat/lon with a "," instead of a "."

**Comment by forrestguice** [comment] 2016-08-08 22:10
ok. I have been mixing up the various formats described in iso 6709 and the format we're actually working with, which is `decimal degrees` (DD). I can't seem to find a full copy of iso 6709, but I've read elsewhere that it recommends decimal degrees as the exchange format, which would forbid localization. ..so as long as the user understands they are viewing/entering decimal degrees, there shouldn't be any confusion. *heh* O.o

we can localize and display to one of those other formats as a new feature, but for now I'm just going to fix the line that's erroneously reformatting the decimal degree coordinates.

someone please set me straight here. :\

**Comment by forrestguice** [comment] 2016-08-10 18:23
I'm thinking I need to cut another release like right now before more people run into something like #32. 
I'm a little worried I'm about to break it again.

@verdulo are you able to build the app? if so do the latest changes test right? I need a better test strategy. I could attach self-signed apks to an issue, but I'm not sure thats sane.

**Comment by forrestguice** [comment] 2016-08-10 18:49
or i could just press this "release" button. lol. and then patch it after i break it, and press the button again. but I would really like to avoid cluttering the releases page w/ broken stuff, as fdroid scans those tags when updating.

**Comment by forrestguice** [comment] 2016-08-13 19:10
fixed in v0.2.0

**Closed by forrestguice** 2016-08-13 19:10 UTC
Labels: bug
