### ISSUE TITLE
crash after changing sun data source

### ISSUE THREAD

**Issue by anlalalu** [forrestguice/SuntimesWidget#377] opened 2019-12-12 11:21 UTC
###### Reproduction Steps

1. change the sun data source to 'sunrisesunsetlib' in settings interface
2. tap 'more options' in main interface
3. tap 'world map'

###### crash stack trace
FATAL EXCEPTION: AsyncTask #2
                                                 Process: com.forrestguice.suntimeswidget, PID: 8700
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:841)
                                                  Caused by: java.lang.NullPointerException
                                                     at com.forrestguice.suntimeswidget.map.WorldMapTask$WorldMapProjection.gha(WorldMapTask.java:189)
                                                     at com.forrestguice.suntimeswidget.map.WorldMapEquiazimuthal.makeBitmap(WorldMapEquiazimuthal.java:166)
                                                     at com.forrestguice.suntimeswidget.map.WorldMapTask.makeBitmap(WorldMapTask.java:78)
                                                     at com.forrestguice.suntimeswidget.map.WorldMapTask.doInBackground(WorldMapTask.java:73)
                                                     at com.forrestguice.suntimeswidget.map.WorldMapTask.doInBackground(WorldMapTask.java:37)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)

###### Debug info

Android Version = 4.4.4

**Comment by forrestguice** [comment] 2019-12-12 17:16
Hi, thank you for the crash log.
What is the app version? Also, where did you download it from (F-Droid?)

I can't reproduce it on the latest version (v0.12.3), but it looks familiar.. I think this is a bug (https://github.com/forrestguice/SuntimesWidget/issues/309) that was fixed in v0.11.2. The older data sources aren't able to report position information - the expected behavior is a "not supported" message.

**Closed** 2020-01-07 18:21 UTC
Labels: duplicate
