### ISSUE TITLE
AST Alarm time drifts 

### ISSUE THREAD

**Issue by skymandr** [forrestguice/SuntimesWidget#715] opened 2023-06-22 09:35 UTC
**Describe the bug**
I have two alarms set to different times, 21:21 and 5:55 Apparent Solar Time (AST). However, at the time of writing, these have drifted to 21:11 and 5:45 respectively.

Additionally, when setting the alarms, the time often (but not always) drifts twice: first when picking 21:21, the result after accepting the time often ticks down one minute to 21:20, then when I save the alarm it often ticks down a further minute to 21:19. By selecting 21:23 I can usually get the alarm to display 21:21 in the overview, but the exact behaviour varies a bit.

I report these together, because I think they probably have the same root cause, though I could be mistaken.

(I really like the app by the way, so thank you very much for developing it!)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Alarms'
2. Click on an alarm
3. Scroll down to schedule
4. Set alarm time based on apparent solar time
  4a. Click ok. This will sometimes make the time you set drift by a minute
5. Save alarm
  5a. This will sometimes make the time you set drift by a further minute
6. Wait. In a few days the alarm time has drifted from what you have set.

**Expected behaviour**
I would have expected the time I set, however arbitrary, to be respected, both over time and when setting the alarm. Perhaps the behaviour is as intended, but it seems weird to me and I don't understand the logic in that case.

**Screenshots**
I can provide screenshots if necessary.

**Version Info:**
 - App Version: 0.15.4
 - Android Version: 12
 - Device Model: Galaxy A21s

**Additional context**
None that I can thing of.

**Comment by forrestguice** [comment] 2023-06-25 17:39
Hi. Thanks for taking time to report.

I assume that these are "repeating alarms", and that the drift (~a minute) occurs whenever the alarm gets (re)scheduled. So after a week of continual rescheduling the alarm has drifted ~10 minutes. This is in addition to some initial drift that is triggered after choosing the time, and again after saving the alarm. I think you are probably right that these have the same root cause.

I'll try to look closely at this in the next few weeks. The features including "apparent solar time" aren't well tested, and I've already discovered another bug while trying to track down this one.

What is your longitude? This may help reproduce it.
A set of before/after screenshots might also contain some clues. I wouldn't mind glancing at the selection dialog, the alarm edit screen (showing initial drift), and the alarm list (after creating the alarm, and again after the alarm has drifted some time).

**Comment by skymandr** [comment] 2023-06-26 07:57
> What is your longitude? This may help reproduce it.

My longitude is approximately 57˚N.

> A set of before/after screenshots might also contain some clues. I wouldn't mind glancing at the selection dialog, the alarm edit screen (showing initial drift), and the alarm list (after creating the alarm, and again after the alarm has drifted some time).

Ok, I'll try to fix that today. Thanks for taking the time (insert pun here)!

**Comment by skymandr** [comment] 2023-06-26 11:57
# Selecting 5:55
![Screenshot_20230626-134930_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/358614/03515546-c43d-472e-895a-ddde8ccf5baa)

# Pressing OK, time is now 5:54
![Screenshot_20230626-134940_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/358614/4b971077-cf14-456d-aa23-34644ad30728)

# Saving, time is now 5:52
![Screenshot_20230626-134948_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/358614/b13c86b3-7a5b-4b99-92dd-b8de6c27abdc)

**Comment by forrestguice** [comment] 2023-06-28 19:59
Thanks. This should be fixed in `v0.15.5`.

I'm able to reproduce it on a newer device (api 30), and emulator (api 33). It doesn't happen with my older device (api 19). I initially failed to reproduce it, so I feared this was going to be difficult to identify.

It's an interesting bug.. The method that schedules alarms is repaired, but the actual underlying cause remains a bit of a mystery. It happens for one Android version and not another, basic tests will pass/fail depending on whether/how they are 'instrumented', etc. A custom TimeZone object is at the heart of the algorithm, so I suspect internal changes in that api are probably responsible.

**Closed** 2023-07-02 23:37 UTC
Labels: bug
