### ISSUE TITLE
force close when adding widget

### ISSUE THREAD

**Issue by nutpantz** [forrestguice/SuntimesWidget#126] opened 2017-12-14 16:42 UTC
With the newest release on fdroid (.51)
I get a force close when adding a widget.
Previous version works fine.
I'm on android 6.01 note 4

**Comment by forrestguice** [comment] 2017-12-14 18:03
well damn, not good. 

I've got a bunch of questions that might help me figure this out quicker, if you'll indulge me ;)
I think a screenshot of the configuration activity (just before the force close, which I assume is happening after clicking "add widget") might be helpful.

which widget? Is it the 1x1 widget that is force closing, or the one that is labeled 2x1? (or maybe both)
which datasource? Is it set to the new default time4a-noaa, or something else? 
which timezone? I'm assuming its probably system timezone.
are you using applying a custom theme (or is it just one of the defaults)?

I

**Comment by forrestguice** [comment] 2017-12-14 18:07
A bunch of code was refactored to expose to the 2x1 widget, and the fact it doesn't happen in 0.5.0 is a good indication I accidentally screwed something up. Thanks for letting me know :\

I'm about to head out of town for the weekend, so probably won't be able to get to this until next week.

**Comment by forrestguice** [comment] 2017-12-14 18:11
If it occurs for all widgets (even the flippable one), I think that indicates something wrong w/ the theming. v0.5.1 applies theme colors to the icons, while v0.5.0 leaves them alone. Anyhow, thinking out loud, gonna get to the bottom of it.

**Comment by nutpantz** [comment] 2017-12-14 18:14
It's s fresh install nothing configured location is default Toronto and all three widgets force close 2x1 closes instantly with no configuring other widget force close a after I hit add widget.
Solar noon does not force close but no widget is added.
I've gone back to the old ver so no rush

**Comment by forrestguice** [comment] 2017-12-14 18:21
thanks, these are some good observations.

**Comment by forrestguice** [comment] 2017-12-14 18:22
misclick ;) 

thanks, these are some good observations.

**Comment by nutpantz** [comment] 2017-12-14 18:22
There seems to be no problem on my note 3 with 442. I also use nova launcher

**Comment by forrestguice** [comment] 2017-12-17 20:27
tested on android 5.1 (22)
I'm able to add the 1x1 and 2x1 widgets without issue, but the flippable widget crashes after clicking "add".. IllegalArgumentException traces back to code that themes icons - `drawable.getIntrinsicWidth()` and `getIntrinsicHeight` returning 0 for some reason. 

Also tested on 19, 16, 15, and 10 - working as expected.
Still haven't tested against android6 yet - I'm running into a bunch of frustrating env related issues, trouble adding new avds, trouble getting the emulator to run, etc. ..fun.

**Comment by forrestguice** [comment] 2017-12-20 02:32
@nutpantz The good news.. I've got the emulator up and running again and was able to test against android 6. lol, what a feat!

The bad news, I can't seem to reproduce the crash w/ the 2x1 widget (only the previously mentioned crash w/ the flippable widget).

If you know how to get the logcat from your device, having a copy of that would be very helpful. However, I think thats way easier said than done. :\ ..but if you have heard of `adb` or know how to plug your device in via usb, you're half way there.

I will attempt to test against a different launcher next. I'm guessing a change to the Manifest might be responsible for it crashing before the config activity is even displayed...

**Comment by nutpantz** [comment] 2017-12-20 04:00
Try this


On December 19, 2017 6:32:11 PM PST, Forrest Guice <notifications@github.com> wrote:
>@nutpantz The good news.. I've got the emulator up and running again
>and was able to test against android 6. lol, what a feat!
>
>The bad news, I can't seem to reproduce the crash w/ the 2x1 widget
>(only the previously mentioned crash w/ the flippable widget).
>
>If you know how to get the logcat from your device, having a copy of
>that would be very helpful. However, I think thats way easier said than
>done. :\ ..but if you have heard of `adb` or know how to plug your
>device in via usb, you're half way there.
>
>I will attempt to test against a different launcher next. I'm guessing
>a change to the Manifest might be responsible for it crashing before
>the config activity is even displayed...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/forrestguice/SuntimesWidget/issues/126#issuecomment-352947340

Unknown element under <manifest>: meta-data at /data/app/com.forrestguice.suntimeswidget-2/base.apk Binary XML file line #18

put: /data/app/com.forrestguice.suntimeswidget-2

Send intent for com.forrestguice.suntimeswidget

mIntentRecvWidget widget add : com.forrestguice.suntimeswidget

New widget add: Add com.forrestguice.suntimeswidget into list.

Start proc 20437:com.forrestguice.suntimeswidget/u0a217 for broadcast-2 com.forrestguice.suntimeswidget/.SuntimesWidget0_2x1

SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.forrestguice.suntimeswidget 

identifyGamePackage. com.forrestguice.suntimeswidget

Gamemode - return 0,  when calling  identifyForegroundApp(com.forrestguice.suntimeswidget)

addAppToken: AppWindowToken{809d801 token=Token{85bc9e8 ActivityRecord{3ae470b u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0_2x1 t857}}} to stack=0 task=857 at 1

 Launching com.forrestguice.suntimeswidget, updated priority

NotifyRunnable. pkg: com.forrestguice.suntimeswidget, type: 4, isMinimized: false, isTunableApp: false

[foreground] Process cur broadcast BroadcastRecord{1688639 u0 android.appwidget.action.APPWIDGET_ENABLED qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{b7cb47e 20437:com.forrestguice.suntimeswidget/u0a217}

InputChannelName : a6308fb Starting com.forrestguice.suntimeswidget

ClassLoader referenced unknown path: /data/app/com.forrestguice.suntimeswidget-2/lib/arm

Hooking package=com.forrestguice.suntimeswidget

identifyGamePackage. com.forrestguice.suntimeswidget

Finishing drawing window Window{a6308fb u0 d0 Starting com.forrestguice.suntimeswidget}: mDrawState=DRAW_PENDING

Finishing drawing window Window{a6308fb u0 d0 Starting com.forrestguice.suntimeswidget}: mDrawState=COMMIT_DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{a6308fb u0 d0 Starting com.forrestguice.suntimeswidget}

identifyGamePackage. com.forrestguice.suntimeswidget

InputChannelName : 5e25c48 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0_2x1

[foreground] Process cur broadcast BroadcastRecord{ec74006 u0 android.appwidget.action.APPWIDGET_UPDATE qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{b7cb47e 20437:com.forrestguice.suntimeswidget/u0a217}

Process: com.forrestguice.suntimeswidget, PID: 20437

java.lang.RuntimeException: Unable to start receiver com.forrestguice.suntimeswidget.SuntimesWidget0_2x1: java.lang.IllegalArgumentException: width and height must be > 0

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:776)

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:718)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout_1x1_0.themeViews(SuntimesLayout_1x1_0.java:98)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout.themeViews(SuntimesLayout.java:93)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:309)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:293)

	at com.forrestguice.suntimeswidget.SuntimesWidget0_2x1.updateWidget(SuntimesWidget0_2x1.java:55)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.onUpdate(SuntimesWidget0.java:181)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.onReceive(SuntimesWidget0.java:93)

  Force finishing activity com.forrestguice.suntimeswidget/.SuntimesConfigActivity0_2x1

InputChannelName : d5d85f2 Application Error: com.forrestguice.suntimeswidget

manageDisableList userId=0 what=0x0 pkg=Window{d5d85f2 u0 d0 Application Error: com.forrestguice.suntimeswidget}

Finishing drawing window Window{d5d85f2 u0 d0 Application Error: com.forrestguice.suntimeswidget}: mDrawState=DRAW_PENDING

Finishing drawing window Window{d5d85f2 u0 d0 Application Error: com.forrestguice.suntimeswidget}: mDrawState=HAS_DRAWN

Activity pause timeout for ActivityRecord{3ae470b u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0_2x1 t857 f}

[background] Process cur broadcast BroadcastRecord{447a8bb u0 android.appwidget.action.APPWIDGET_DELETED qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{b7cb47e 20437:com.forrestguice.suntimeswidget/u0a217}

manageDisableList userId=0 what=0x0 pkg=Window{d5d85f2 u0 d0 Application Error: com.forrestguice.suntimeswidget}

Process com.forrestguice.suntimeswidget (pid 20437)(adj 0) has died(125,1079)

isAutoRunBlockedApp:: com.forrestguice.suntimeswidget, Auto Run ON

WIN DEATH: Window{5e25c48 u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0_2x1}

Start proc 20858:com.forrestguice.suntimeswidget/u0a217 for broadcast-3 com.forrestguice.suntimeswidget/.SuntimesWidget0_2x1

SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.forrestguice.suntimeswidget 

[background] Process cur broadcast BroadcastRecord{53f62c6 u0 android.appwidget.action.APPWIDGET_DISABLED qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{7399287 20858:com.forrestguice.suntimeswidget/u0a217}

ClassLoader referenced unknown path: /data/app/com.forrestguice.suntimeswidget-2/lib/arm

Hooking package=com.forrestguice.suntimeswidget

 remove PendingIntent] PendingIntent{42049e: PendingIntentRecord{9b84b7f com.forrestguice.suntimeswidget broadcastIntent}}

Send intent for com.forrestguice.suntimeswidget

mIntentRecvWidget widget add : com.forrestguice.suntimeswidget

New widget add: com.forrestguice.suntimeswidget already exist in list.

[foreground] Process cur broadcast BroadcastRecord{db3074c u0 android.appwidget.action.APPWIDGET_ENABLED qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{7399287 20858:com.forrestguice.suntimeswidget/u0a217}

identifyGamePackage. com.forrestguice.suntimeswidget

Gamemode - return 0,  when calling  identifyForegroundApp(com.forrestguice.suntimeswidget)

addAppToken: AppWindowToken{10209b token=Token{ac5ccaa ActivityRecord{23b7395 u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0 t857}}} to stack=0 task=857 at 1

[foreground] Process cur broadcast BroadcastRecord{62cb411 u0 android.appwidget.action.APPWIDGET_UPDATE qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{7399287 20858:com.forrestguice.suntimeswidget/u0a217}

 Launching com.forrestguice.suntimeswidget, updated priority

NotifyRunnable. pkg: com.forrestguice.suntimeswidget, type: 4, isMinimized: false, isTunableApp: false

Process: com.forrestguice.suntimeswidget, PID: 20858

java.lang.RuntimeException: Unable to start receiver com.forrestguice.suntimeswidget.SuntimesWidget0: java.lang.IllegalArgumentException: width and height must be > 0

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:776)

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:718)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout_1x1_0.themeViews(SuntimesLayout_1x1_0.java:98)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout.themeViews(SuntimesLayout.java:93)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:309)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:293)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateWidget(SuntimesWidget0.java:190)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.onUpdate(SuntimesWidget0.java:181)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.onReceive(SuntimesWidget0.java:93)

Process com.forrestguice.suntimeswidget has crashed too many times: killing!

  Force finishing activity com.forrestguice.suntimeswidget/.SuntimesConfigActivity0

Wtf, activity ActivityRecord{23b7395 u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0 t857 f} in proc activity list not using proc ProcessRecord{7399287 20858:com.forrestguice.suntimeswidget/u0a217}?!? Using null instead.

Killing 20858:com.forrestguice.suntimeswidget/u0a217 (adj 9): crash

isAutoRunBlockedApp:: com.forrestguice.suntimeswidget, Auto Run ON

Unable to launch app com.forrestguice.suntimeswidget/10217 for broadcast Intent { act=android.appwidget.action.APPWIDGET_DELETED flg=0x10 cmp=com.forrestguice.suntimeswidget/.SuntimesWidget0 (has extras) }: process is bad

Unable to launch app com.forrestguice.suntimeswidget/10217 for broadcast Intent { act=android.appwidget.action.APPWIDGET_DISABLED flg=0x10 cmp=com.forrestguice.suntimeswidget/.SuntimesWidget0 }: process is bad

mIntentRecvWidget widget add : com.forrestguice.suntimeswidget

New widget add: com.forrestguice.suntimeswidget already exist in list.

Send intent for com.forrestguice.suntimeswidget

Unable to launch app com.forrestguice.suntimeswidget/10217 for broadcast Intent { act=android.appwidget.action.APPWIDGET_ENABLED flg=0x10000010 cmp=com.forrestguice.suntimeswidget/.SuntimesWidget0 }: process is bad

Unable to launch app com.forrestguice.suntimeswidget/10217 for broadcast Intent { act=android.appwidget.action.APPWIDGET_UPDATE flg=0x14000010 cmp=com.forrestguice.suntimeswidget/.SuntimesWidget0 (has extras) }: process is bad

identifyGamePackage. com.forrestguice.suntimeswidget

Gamemode - return 0,  when calling  identifyForegroundApp(com.forrestguice.suntimeswidget)

addAppToken: AppWindowToken{fa31e14 token=Token{8e2e067 ActivityRecord{e67bc26 u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0 t857}}} to stack=0 task=857 at 1

InputChannelName : 4ee6075 Starting com.forrestguice.suntimeswidget

Start proc 21087:com.forrestguice.suntimeswidget/u0a217 for activity com.forrestguice.suntimeswidget/.SuntimesConfigActivity0

SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.forrestguice.suntimeswidget 

Finishing drawing window Window{4ee6075 u0 d0 Starting com.forrestguice.suntimeswidget}: mDrawState=DRAW_PENDING

 Launching com.forrestguice.suntimeswidget, updated priority

NotifyRunnable. pkg: com.forrestguice.suntimeswidget, type: 4, isMinimized: false, isTunableApp: false

ClassLoader referenced unknown path: /data/app/com.forrestguice.suntimeswidget-2/lib/arm

Hooking package=com.forrestguice.suntimeswidget

manageDisableList userId=0 what=0x0 pkg=Window{4ee6075 u0 d0 Starting com.forrestguice.suntimeswidget}

identifyGamePackage. com.forrestguice.suntimeswidget

identifyGamePackage. com.forrestguice.suntimeswidget

InputChannelName : a52066b com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0

DTS_GLAPI : DTS is not allowed for Package : com.forrestguice.suntimeswidget

Finishing drawing window Window{a52066b u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0}: mDrawState=DRAW_PENDING

Displayed com.forrestguice.suntimeswidget/.SuntimesConfigActivity0: +1s37ms (total +14s228ms)

Timeline: Activity_windows_visible id: ActivityRecord{e67bc26 u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0 t857} time:208403

Finishing drawing window Window{a52066b u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0}: mDrawState=HAS_DRAWN

Process: com.forrestguice.suntimeswidget, PID: 21087

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:776)

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:718)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout_1x1_0.themeViews(SuntimesLayout_1x1_0.java:98)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout.themeViews(SuntimesLayout.java:93)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:309)

	at com.forrestguice.suntimeswidget.SuntimesWidget0.updateAppWidget(SuntimesWidget0.java:293)

	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.updateWidget(SuntimesConfigActivity0.java:923)

	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.addWidget(SuntimesConfigActivity0.java:906)

	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0$14.onClick(SuntimesConfigActivity0.java:892)

  Force finishing activity com.forrestguice.suntimeswidget/.SuntimesConfigActivity0

InputChannelName : ec2aeca Application Error: com.forrestguice.suntimeswidget

manageDisableList userId=0 what=0x0 pkg=Window{ec2aeca u0 d0 Application Error: com.forrestguice.suntimeswidget}

Finishing drawing window Window{ec2aeca u0 d0 Application Error: com.forrestguice.suntimeswidget}: mDrawState=DRAW_PENDING

Finishing drawing window Window{ec2aeca u0 d0 Application Error: com.forrestguice.suntimeswidget}: mDrawState=HAS_DRAWN

Activity pause timeout for ActivityRecord{e67bc26 u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity0 t857 f}

[background] Process cur broadcast BroadcastRecord{7a814b1 u0 android.appwidget.action.APPWIDGET_DELETED qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{ac4ed96 21087:com.forrestguice.suntimeswidget/u0a217}

manageDisableList userId=0 what=0x0 pkg=Window{ec2aeca u0 d0 Application Error: com.forrestguice.suntimeswidget}

Process com.forrestguice.suntimeswidget (pid 21087)(adj 0) has died(90,1079)

isAutoRunBlockedApp:: com.forrestguice.suntimeswidget, Auto Run ON

WIN DEATH: Window{a52066b u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity0}

Start proc 21712:com.forrestguice.suntimeswidget/u0a217 for broadcast-3 com.forrestguice.suntimeswidget/.SuntimesWidget0

SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.forrestguice.suntimeswidget 

[background] Process cur broadcast BroadcastRecord{3b1e846 u0 android.appwidget.action.APPWIDGET_DISABLED qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{3a96a07 21712:com.forrestguice.suntimeswidget/u0a217}

ClassLoader referenced unknown path: /data/app/com.forrestguice.suntimeswidget-2/lib/arm

Hooking package=com.forrestguice.suntimeswidget

 remove PendingIntent] PendingIntent{ecfba1e: PendingIntentRecord{a5b92ff com.forrestguice.suntimeswidget broadcastIntent}}

Send intent for com.forrestguice.suntimeswidget

mIntentRecvWidget widget add : com.forrestguice.suntimeswidget

New widget add: com.forrestguice.suntimeswidget already exist in list.

[foreground] Process cur broadcast BroadcastRecord{178cc u0 android.appwidget.action.APPWIDGET_ENABLED qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{3a96a07 21712:com.forrestguice.suntimeswidget/u0a217}

[foreground] Process cur broadcast BroadcastRecord{395a2a u0 android.appwidget.action.APPWIDGET_UPDATE qIdx=2}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{3a96a07 21712:com.forrestguice.suntimeswidget/u0a217}

identifyGamePackage. com.forrestguice.suntimeswidget

Gamemode - return 0,  when calling  identifyForegroundApp(com.forrestguice.suntimeswidget)

addAppToken: AppWindowToken{449bf91 token=Token{e3355b8 ActivityRecord{860601b u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity1 t857}}} to stack=0 task=857 at 1

 Launching com.forrestguice.suntimeswidget, updated priority

NotifyRunnable. pkg: com.forrestguice.suntimeswidget, type: 4, isMinimized: false, isTunableApp: false

identifyGamePackage. com.forrestguice.suntimeswidget

identifyGamePackage. com.forrestguice.suntimeswidget

InputChannelName : 38539ef com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1

manageDisableList userId=0 what=0x0 pkg=Window{38539ef u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1}

DTS_GLAPI : DTS is not allowed for Package : com.forrestguice.suntimeswidget

Finishing drawing window Window{38539ef u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{38539ef u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1}

Displayed com.forrestguice.suntimeswidget/.SuntimesConfigActivity1: +757ms

Finishing drawing window Window{38539ef u0 d0 com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity1}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{860601b u0 com.forrestguice.suntimeswidget/.SuntimesConfigActivity1 t857} time:218259

Process: com.forrestguice.suntimeswidget, PID: 21712

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:776)

	at com.forrestguice.suntimeswidget.SuntimesUtils.drawableToBitmap(SuntimesUtils.java:718)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout_1x1_1.themeViews(SuntimesLayout_1x1_1.java:81)

	at com.forrestguice.suntimeswidget.layouts.SuntimesLayout.themeViews(SuntimesLayout.java:93)

	at com.forrestguice.suntimeswidget.SuntimesWidget1RemoteViewsFactory.getViewAt(SuntimesWidget1Service.java:152)

Process com.forrestguice.suntimeswidget has crashed too many times: killing!

Killing 21712:com.forrestguice.suntimeswidget/u0a217 (adj 1): crash

isAutoRunBlockedApp:: com.forrestguice.suntimeswidget, Auto Run ON

**Comment by nutpantz** [comment] 2017-12-20 04:01
ok that was supposed to be an attachment..
I added each widget one at a time with no changes to anything.
Hope it helps.

**Comment by nutpantz** [comment] 2017-12-20 04:18
One new thing
I noticed that at some point there was a widget added. It was just invisible  as when I held my finger down in the spot where I added three widgets i got the option to resize, remove etc the invisible widget.

**Comment by forrestguice** [comment] 2017-12-20 04:30
awesome, thanks for the log. I think I understand whats happening now. It appears to be the same error each time, though its narrowly avoided twice on the emulator (leaving the one time I notice it). I think the fix I applied earlier should fix all widgets.

I've noticed the "invisible widget" issue but not really sure what to make of it. I think it only happens w/ the flippable widget, but every time it does happen there is some other problem (that has prevented the widget from updating). 

First time I noticed it I attempted to add a flippable widget and nothing appeared, so added a second widget. Then later I notice there are two widgets available in the reconfigure list (and if you go looking for it its possible to resize and it appears). hrm. I've noticed if you wait long enough (a day) the update is triggered and the widget appears. Seems to be an issue w/ the very first time the widget updates. weird.

**Comment by forrestguice** [comment] 2017-12-20 04:55
ok. I'm going to tag a release next day or so (v0.5.2). You can close this issue if it tests ok (or post another log and we'll keep working at it).

If you notice the "invisible widget" behavior again, open a new issue. I think its only tangentially related, happens when something else is broken - I'm hoping not to see it again under normal operation.

**Comment by forrestguice** [comment] 2018-02-16 07:50
I'm assuming this is resolved, so closing this.

**Closed by forrestguice** 2018-02-16 07:50 UTC
Labels: api22, api23, bug
