### ISSUE TITLE
Sun/Moon Drop-downs show wrong data

### ISSUE THREAD

**Issue by gb-dursley** [forrestguice/SuntimesWidget#613] opened 2022-07-21 11:51 UTC
**Describe the bug**
If the following location is different from current system location, time zone set match set location, and date to several months in the future, then the data in the Sun/Moon drop-downs is different to that in the main display:

**To Reproduce**
Set:
a. Location to somewhere in a different time zone (e.g. Athens)
b. Time zone to match the new location (Z+2, DST+1)
c. Date to 30/09/22

Data shown looks sane (but not easy to check).

BUT:
1) tap on Solar noon for **Sun Position** drop-down: data appears for current **system time/date** (and location?)
2) tap on Moon for **Moon** drop-down shows moon data consistent with that shown for **set date** (and location?), BUT sliding the date backwards or forwards a day at a time, the data in the Moon drop-down (which has no date!) doesn't change.
These two major and inconsistent defects call into question the reliability of all data shown by the app. 

**Expected behavior**
1) it's counter-intuitive to tap on Solar _Noon_ to get solar data for other times (sunrise, current, sunset). The Solar Data in the **Sun Position** drop-down should be for the Date, Time Zone and Location shown in the main display rather for System data!
2) the Lunar data in the **Moon** drop-down should be for the Date, Time Zone and Location shown in the main display and to inspire any confidence, the date and time must be shown in the drop-down.

**Screenshots**
N/A - posting on a laptop (too painful on tablet).

**Version Info:**
 - App Version: 0.14.6 (from F-Droid)
 - Android Version: 9
 - Device Model: Galaxy Tab S3 SM-T825

**Additional context**
I'm planning an evening photo-shoot on a Greek mountain in September, so I want to know local times (and bearings) of sunset, moon-rise and -set and moon-phase; so I want to select a week when: the sunset won't be behind another, taller, mountain; the moon will be between 1st and 3rd qtrs and will be high in the sky at sunset and on a bearing to give some background light and so that walking back down the mountain won't be in pitch dark!

**Comment by forrestguice** [comment] 2022-07-21 21:12
Hi. Thanks for taking time report.

I've read this a few times now, and think I understand. There are a couple confounding details (location, timezone, etc), but what I think is most relevant is the use of `Set Date` (the final step in steps to reproduce).

The first two steps, configuring location and timezone to match, describe what I consider the average use case. I'm not sure what is meant by "current system location". All of the data is location dependent (as configured in the Location dialog), and the app only understands the latitude and longitude as configured. It does offer a "current" location mode - what this does is (frequently) reconfigure the app. Its always on the user to match the time zone. 

I think its the final step that triggers/reveals the bug.. By using `Set Date`, all of the views get "re-centered" around the given date (as if it were today). There is another (less convenient) way of checking dates in the future, which is to actually change the device's date/time, however this doesn't trigger the bug(s).

> tap on Solar noon for Sun Position drop-down: data appears for current system time/date

This dialog should open to the date displayed on the card. So if tapped from the "today" card it should open to today, and if tapped from "future (+17)", it should open to 17 days from today. When using `Set Date` to 30/09/22, the main card should display that date as "today" (and the dialog should open to that date). Instead, its opening to the current system date (ignores the setting). Another detail.. It seems if I flip the main card forward or back a few pages, then trigger the dialog, it opens to the expected date. So the bug seems limited to the yesterday/today/tomorrow cards.

> tap on Moon for Moon drop-down shows moon data consistent with that shown for set date (and location?), BUT sliding the date backwards or forwards a day at a time, the data in the Moon drop-down (which has no date!) doesn't change

The short explanation is the Sun Position dialog was extended recently to allow navigating forward/backward, and was previously limited to displaying just "today". The Moon dialog is still limited like this and is always centered on the "today" card. So now these dialogs aren't consistent - I agree it doesn't inspire confidence, especially if I'm already uncertain what I'm looking it. 

I consider the issue with the Sun Position dialog to a be bug (will be fixed asap in a upcoming patch). I think the issue with the Moon dialog is more of an enhancement (will be expanded in an upcoming minor version), but might add another label (today's date) to the top of that dialog in the meantime to reduce confusion.

**Comment by forrestguice** [comment] 2022-07-21 21:32
Incidentally, I've been considering removing `Set Date` and replacing it with `Scroll to Date`. It seems like an obvious feature but this is missing..

This would instead cause the card to jump to a given date (but "today" would always match the system date). `Set Date` is actually an artifact from before the app supported scrolling the card (and was at the time limited to "yesterday/today/tomorrow").

**Comment by forrestguice** [comment] 2022-07-21 23:56
> Instead, its opening to the current system date (ignores the setting). 

I think more specifically, the problem is that the dialog is always centered on the system date, and completely ignores the date setting. By flipping forward/back and triggering the dialog, it does bring up the expected dates, but then clicking reset (far left button) brings it back to the system date.

**Comment by Timo-Fi** [comment] 2022-07-22 04:14
In the Sun Position dialog, when one taps the title element (at the top-left corner) a drop-down opens for choice of a time system, perhaps this has something to do with the case.

**Comment by forrestguice** [comment] 2022-07-22 15:33
@Timo-Fi It's not related, but I appreciate you taking a look. What I've discovered, digging into the code, is that I basically neglected to implement `Set Date` when I last rewrote this dialog. It always centers itself on the system date because that's how it was written. It seems the older `Set Date` feature completely slipped my mind.

**Closed** 2023-02-01 06:25 UTC
Labels: bug
