### ISSUE TITLE
Shows wrong rise time for Latvia, Riga

### ISSUE THREAD

**Issue by iav** [forrestguice/SuntimesWidget#32] opened 2016-08-10 03:07 UTC
Subj.

**Comment by forrestguice** [comment] 2016-08-10 14:03
the times are calculated by sunrisesunsetlib-java -> you can report an issue there https://github.com/mikereedell/sunrisesunsetlib-java/issues

...but (from the sunrisesunsetlib-java readme) you seem to be leaving out all the important information..

> When filing a bug report, please include the following information:
> 
> Date sunrise/set calculation was being run for.
> Latitude/longitute sunrise/set calculation was being run for.
> Timezone (either "America/New_York" or GMT-0500)

**Comment by forrestguice** [comment] 2016-08-10 14:53
in addition to reporting upstream, I would also be interested in getting that info from you (but no guarantee I can do anything about it).

the date, lat/lon, timezone, the time you were expecting to see (and source of that info, e.g. wunderground), and the time you are actually seeing.

**Comment by iav** [comment] 2016-08-10 17:23
![screenshot_2016-08-06-20-59-02](https://cloud.githubusercontent.com/assets/325961/17563465/2d50a2a6-5f38-11e6-86f2-ea932501d5c7.png)
Real time should be like 22

**Comment by iav** [comment] 2016-08-10 17:28
Just for reference - correct data about 5:44-21:12

**Comment by forrestguice** [comment] 2016-08-10 17:29
ahh, that screenshot helps a lot! I see commas in your lat/lon - I think this is related to #29.

**Comment by verdulo** [comment] 2016-08-10 17:30
Maybe this bug is related to: https://github.com/forrestguice/SuntimesWidget/issues/29; click on the "Needle" icon, and see the coordinates, you're in reality getting times for: Lat: 34,54 N, Long: 112,46 S probably.

**Comment by forrestguice** [comment] 2016-08-10 17:36
try entering the lat/lon manually using a "." instead "," as the decimal separator. does that seem to fix it?

..if that is possible that is. I'm not entirely sure the keyboard shows the right symbols; "." vs ","

**Comment by iav** [comment] 2016-08-11 01:21
I can't enter manually - I can't find a way for it.
taps on a numbers ob a screenshot not gives a fields for enter and not open a keyboard.
By the way, 2 separate field for coordinates makes harder pasting from the clipboard.
![2016-08-11 01 17 27](https://cloud.githubusercontent.com/assets/325961/17576400/1777bd5a-5f7b-11e6-8c00-9731bcd31925.png)

**Comment by forrestguice** [comment] 2016-08-11 06:48
tapping the location icon (left of name) should enable those lat/lon fields, and make that name spinner into an edittext. tapping it again should save and turn name back into a spinner. it should then be possible to select previous locations from the spinner.

good point about two fields vs one, although I really don't trust most people to know that the format is `lan, lon` when doing it by hand. I'll look into making the copy/paste situation better. maybe a paste on either field w/ valid `lat, lon` fills both fields.

**Comment by forrestguice** [comment] 2016-08-11 06:52
![1777bd5a-5f7b-11e6-8c00-9731bcd31925](https://cloud.githubusercontent.com/assets/10246147/17580691/6dcccef0-5f55-11e6-8b9d-5274c6bd082b.png)

**Comment by forrestguice** [comment] 2016-08-11 07:00
also, it should be possible to fill those lat/lon fields automatically from other apps that offer an action to view a location. similar to the way the map icon in the action bar pops a map activity chooser, if you do that from another app, the "Suntimes" app should show up in the list, and selecting it should pop that Location dialog and paste to the fields.

**Comment by iav** [comment] 2016-08-12 00:23
With dots looks more reasonable
![2016-08-12 00 19 32](https://cloud.githubusercontent.com/assets/325961/17609262/e9c0e80c-603b-11e6-8db6-481dabfa452c.png)

It's not easy to understand to push to marker to edit data. Touching to data user want to edit and edit seems more intuitive.

**Comment by forrestguice** [comment] 2016-08-12 01:03
I understand what you mean. It looks more like decoration and not much like a button. Touching the fields to enable editing seems like a good idea.

**Comment by forrestguice** [comment] 2016-08-13 19:11
duplicate of #29, fixed in v0.2.0

**Closed by forrestguice** 2016-08-13 19:11 UTC
Labels: bug, duplicate
