### ISSUE TITLE
Error upon opening the app for the first time

### ISSUE THREAD

**Issue by Kodmod** [forrestguice/SuntimesWidget#564] opened 2022-02-26 19:01 UTC
A dialogue box comes up when I first open the app:

> This app was built for an older version of Android and may not work properly. Try checking for updates, or contact the developer.

I can tap `OK` and ignore the warning but the app is really unstable (crashing when I set the location, for example).

I'm running A12.

**Comment by forrestguice** [comment] 2022-02-26 20:36
The app is built for Android 7 to maintain backward compatibility with really old devices. It'll be updated for Android 12 eventually (but I'm really in no rush).

The crash you are describing is a duplicate of https://github.com/forrestguice/SuntimesWidget/issues/556, which is fixed in `v0.14.1`. It should be on F-Droid within the next few days.

**Closed by forrestguice** 2022-02-26 20:36 UTC

**Comment by forrestguice** [comment] 2022-03-04 02:39
`v0.14.1` should be on F-Droid now. Please let me know if you run into any additional crashes - fixing problems like these is a priority. They definitely seem more likely after a big release (v0.14.0) after a bunch of code is added.

Also, thank you for letting me know about the "older version" message. That's a little annoying, but afaik its not actually an issue. It should be unrelated to crashes or other bugs you might find.
